# Generated by Django 3.0.7 on 2020-07-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='std_class',
            field=models.CharField(blank=True, max_length=302),
        ),
    ]
